doc: fix a typo and minor grammar issue in PRACTICES.md
chainflip-io/chainflip-backend pull request #4434
Opened 2024-01-19 16:41 UTC by gcbrun

# Pull Request

Typo and grammar fix for a documentation file.

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [x] I have updated documentation where appropriate.

## Summary

I was reading over the practices.md file and noticed a small typo and a grammar issue. Very minor fix.

2024-01-19 17:46 UTC, dandanlen approved these changes
Thanks 👌

2024-01-19 18:34 UTC, kylezs requested changes

2024-01-19 18:34 UTC, kylezs commented on PRACTICES.md
> +# Maintainance
```suggestion
# Maintenance
```

2024-01-20 07:46 UTC, kylezs approved these changes

2024-01-22 15:39 UTC, kylezs commented
> hmm not sure why the test failed

It's because you're making the PR from a fork, and our CI doesn't expose the secrets that would allow it... you're the first external contributor, so we're looking at a way to allow the CI to run for non Chainflip Labs people too :)

2024-03-25 15:18 UTC, closed without merging