fix(chainflip-broker-api): replace u128 with NumberOrHex
chainflip-io/chainflip-backend pull request #4656
Opened 2024-03-18 13:18 UTC by acdibble

# Pull Request

## Checklist

Please conduct a thorough self-review before opening the PR.

- [ ] I am confident that the code works.
- [ ] I have updated documentation where appropriate.

## Summary

For consistency, this should return `NumberOrHex` instead of `u128`. `u128` is too large to be safely represented in JSON, but in this case there shouldn't be any issues because the fee shouldn't exceed 2^53 - 1 (at least immediately).

2024-03-18 13:44 UTC, marcellorigotti approved these changes

2024-03-19 17:08 UTC, AlastairHolmes requested changes
Please use U128 or U256. We are trying to move away from NumberOrHex.

2024-03-19 17:11 UTC, AlastairHolmes commented
Also I believe this is a breaking change right?

2024-03-19 19:01 UTC, acdibble commented
Actually I looked into it and the u128 will get serialized to a string.

2024-03-19 19:07 UTC, acdibble commented
> Also I believe this is a breaking change right?

It won't be if it's included in 1.3 release

2024-03-20 10:43 UTC, AlastairHolmes approved these changes

2024-03-20 10:44 UTC, merged